/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SolarButton {
        /**
          * The text label of the button.
          * @type {string}
          * @default "Button"
         */
        "label": string;
        /**
          * The size of the button. Can be 'small', 'medium', or 'large'.
          * @type {string}
          * @default "medium"
         */
        "size": string;
        /**
          * The type of the button, determining its primary styling. Acceptable values include 'filled', 'outline', etc.
          * @type {string}
          * @default "filled"
         */
        "type": string;
        /**
          * The variant of the button, usually defining its color. Common variants include 'red', 'green', 'blue', etc.
          * @type {string}
          * @default "red"
         */
        "variant": string;
    }
    interface SolarTag {
        "color": string;
        "icon": string;
        "label": string;
        "variant": string;
    }
}
declare global {
    interface HTMLSolarButtonElement extends Components.SolarButton, HTMLStencilElement {
    }
    var HTMLSolarButtonElement: {
        prototype: HTMLSolarButtonElement;
        new (): HTMLSolarButtonElement;
    };
    interface HTMLSolarTagElement extends Components.SolarTag, HTMLStencilElement {
    }
    var HTMLSolarTagElement: {
        prototype: HTMLSolarTagElement;
        new (): HTMLSolarTagElement;
    };
    interface HTMLElementTagNameMap {
        "solar-button": HTMLSolarButtonElement;
        "solar-tag": HTMLSolarTagElement;
    }
}
declare namespace LocalJSX {
    interface SolarButton {
        /**
          * The text label of the button.
          * @type {string}
          * @default "Button"
         */
        "label"?: string;
        /**
          * The size of the button. Can be 'small', 'medium', or 'large'.
          * @type {string}
          * @default "medium"
         */
        "size"?: string;
        /**
          * The type of the button, determining its primary styling. Acceptable values include 'filled', 'outline', etc.
          * @type {string}
          * @default "filled"
         */
        "type"?: string;
        /**
          * The variant of the button, usually defining its color. Common variants include 'red', 'green', 'blue', etc.
          * @type {string}
          * @default "red"
         */
        "variant"?: string;
    }
    interface SolarTag {
        "color"?: string;
        "icon"?: string;
        "label"?: string;
        "variant"?: string;
    }
    interface IntrinsicElements {
        "solar-button": SolarButton;
        "solar-tag": SolarTag;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "solar-button": LocalJSX.SolarButton & JSXBase.HTMLAttributes<HTMLSolarButtonElement>;
            "solar-tag": LocalJSX.SolarTag & JSXBase.HTMLAttributes<HTMLSolarTagElement>;
        }
    }
}
